import {
  boolean, doublePrecision, index, integer, jsonb, pgEnum, pgTable, real,
  smallint, text, timestamp, uniqueIndex, uuid,
} from 'drizzle-orm/pg-core'

export const splitShiftRiskEnum = pgEnum('split_shift_risk', ['none', 'low', 'medium', 'high', 'unknown'])
export const confidenceEnum = pgEnum('confidence', ['confirmed', 'likely', 'unverified'])
export const servicePatternEnum = pgEnum('service_pattern', [
  'lunch_only', 'dinner_only', 'split', 'continuous', 'mixed',
])
/**
 * Establishment categories, ordered by how the work actually feels rather than by cuisine.
 *
 * `brasserie` was merged into `bistro`: Google has no such type and nothing in the data
 * separates the two. `canteen` and `fine_dining` are near-empty in practice and hidden
 * from the filter panel, but `canteen` stays because it short-circuits the split-shift
 * inference — see lib/hours/profile.ts.
 */
export const categoryEnum = pgEnum('category', [
  'restaurant', 'bistro', 'fine_dining', 'fast_food', 'pizzeria',
  'bar', 'cafe', 'bakery', 'caterer', 'canteen', 'other',
])
export const applicationStatusEnum = pgEnum('application_status', [
  'to_contact', 'cv_submitted', 'followed_up', 'interview', 'accepted', 'rejected',
])

/**
 * Registry, raw opening hours and denormalized rhythm profile.
 * The profile is what we filter on: it is computed once in batch, never at query time.
 * See .specs/technique/04-modele-de-donnees.md
 */
export const restaurant = pgTable('restaurant', {
  id: uuid('id').defaultRandom().primaryKey(),

  // Identity — the only Google data we may store durably.
  googlePlaceId: text('google_place_id').notNull().unique(),
  name: text('name').notNull(),
  formattedAddress: text('formatted_address'),
  lat: doublePrecision('lat').notNull(),
  lng: doublePrecision('lng').notNull(),
  googleTypes: text('google_types').array(),
  businessStatus: text('business_status'),
  inseeCode: text('insee_code'),
  commune: text('commune'),
  district: smallint('district'),
  category: categoryEnum('category').notNull().default('other'),
  /** French cuisine label ("japonais", "libanais"), shown as information. Never a filter. */
  cuisine: text('cuisine'),
  phone: text('phone'),

  // SIRENE link — null when unmatched: empty beats wrong.
  siret: text('siret'),
  nafCode: text('naf_code'),
  headcountCode: text('headcount_code'),
  matchScore: real('match_score'),

  // Opening hours. We keep the raw payload next to the computed one so everything can be
  // recomputed without spending another Google call.
  rawOpeningHours: jsonb('raw_opening_hours'),
  hoursFetchedAt: timestamp('hours_fetched_at', { withTimezone: true }),
  hoursExpiresAt: timestamp('hours_expires_at', { withTimezone: true }),
  schedule: jsonb('schedule'),

  // Rhythm profile — the columns we filter on.
  hasHours: boolean('has_hours').notNull().default(false),
  openDaysCount: smallint('open_days_count').notNull().default(0),
  closedDays: smallint('closed_days').array(),
  closedSaturday: boolean('closed_saturday').notNull().default(false),
  closedSunday: boolean('closed_sunday').notNull().default(false),
  closedWeekend: boolean('closed_weekend').notNull().default(false),
  maxConsecutiveDaysOff: smallint('max_consecutive_days_off').notNull().default(0),
  splitDaysCount: smallint('split_days_count').notNull().default(0),
  splitShiftRisk: splitShiftRiskEnum('split_shift_risk').notNull().default('unknown'),
  confidence: confidenceEnum('confidence').notNull().default('unverified'),
  servicePattern: servicePatternEnum('service_pattern'),
  earliestOpenMin: integer('earliest_open_min'),
  latestCloseMin: integer('latest_close_min'),
  weeklyOpenMinutes: integer('weekly_open_minutes').notNull().default(0),
  /** French sentence shown to the user, generated by lib/hours. */
  explanation: text('explanation').notNull().default(''),
  profileComputedAt: timestamp('profile_computed_at', { withTimezone: true }),

  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).defaultNow(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).defaultNow(),
})

/** The only place the user writes — and only about their own job hunt. */
export const application = pgTable('application', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').notNull(),
  restaurantId: uuid('restaurant_id').notNull().references(() => restaurant.id, { onDelete: 'cascade' }),
  status: applicationStatusEnum('status').notNull().default('to_contact'),
  notes: text('notes').notNull().default(''),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (t) => ({
  // An establishment appears only once in a given person's list.
  onePerUser: uniqueIndex('application_user_restaurant').on(t.userId, t.restaurantId),
}))

/**
 * Geocoded SIRENE registry. Two distinct roles:
 *  - supply the headcount bracket, the only open source on team size (D4)
 *  - drive the sweep grid BEFORE the first Google call (D6)
 */
export const sireneEstablishment = pgTable('sirene_establishment', {
  siret: text('siret').primaryKey(),
  siren: text('siren'),
  name: text('name'),
  naf: text('naf'),
  headcountCode: text('headcount_code'),
  communeCode: text('commune_code').notNull(),
  commune: text('commune'),
  address: text('address'),
  postalCode: text('postal_code'),
  lat: doublePrecision('lat'),
  lng: doublePrecision('lng'),
  geocodeScore: real('geocode_score'),
  /** Filled by match:sirene. Null until matched — empty beats wrong. */
  googlePlaceId: text('google_place_id'),
  importedAt: timestamp('imported_at', { withTimezone: true }).defaultNow(),
}, (t) => ({
  byCommune: index('sirene_commune').on(t.communeCode),
  byPosition: index('sirene_position').on(t.lat, t.lng),
}))

export const cellStatusEnum = pgEnum('cell_status', [
  'pending', 'done', 'truncated', 'irreducible', 'failed',
])

/**
 * One cell of the sweep plan: a circle to query.
 * Kept after the fact — it is the trail that lets us spot a silently missed area,
 * the one defect that does not show up in the UI.
 */
export const cell = pgTable('cell', {
  id: uuid('id').defaultRandom().primaryKey(),
  sweepRunId: uuid('sweep_run_id').notNull(),
  lat: doublePrecision('lat').notNull(),
  lng: doublePrecision('lng').notNull(),
  radius: doublePrecision('radius').notNull(),
  /** Number of SIRENE establishments in the cell: the truncation detector. */
  sireneCount: integer('sirene_count').notNull().default(0),
  /** Number of places Google actually returned. 20 = truncated. */
  googleCount: integer('google_count'),
  /** Distance of the farthest result: reveals the radius actually covered. */
  lastResultDistance: doublePrecision('last_result_distance'),
  depth: smallint('depth').notNull().default(0),
  parentId: uuid('parent_id'),
  status: cellStatusEnum('status').notNull().default('pending'),
  queriedAt: timestamp('queried_at', { withTimezone: true }),
}, (t) => ({
  byRun: index('cell_run').on(t.sweepRunId, t.status),
}))

/** Logbook of the project's only costly operation. */
export const sweepRun = pgTable('sweep_run', {
  id: uuid('id').defaultRandom().primaryKey(),
  startedAt: timestamp('started_at', { withTimezone: true }).defaultNow(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  cellsPlanned: integer('cells_planned').notNull().default(0),
  cellsQueried: integer('cells_queried').notNull().default(0),
  callsMade: integer('calls_made').notNull().default(0),
  truncatedUnresolved: integer('truncated_unresolved').notNull().default(0),
  irreducibleCells: integer('irreducible_cells').notNull().default(0),
  placesFound: integer('places_found').notNull().default(0),
  sireneUnmatched: integer('sirene_unmatched').notNull().default(0),
  /** Free text rather than an enum: 'running' | 'succeeded' | 'failed', written by sweep. */
  status: text('status').notNull().default('running'),
  error: text('error'),
})
